name: Build, Test, and Release to GHCR

on:
  push:
    branches: [main]

  schedule:
    - cron: "0 * * * *"  # hourly to check for new duckdb versions

  workflow_dispatch: {}

jobs:
  check-duckdb-version:
    name: Check for new duckdb version
    runs-on: ubuntu-latest
    outputs:
      duckdb_version: ${{ steps.getver.outputs.version }}
    steps:
      - name: Fetch latest DuckDB version from PyPI
        id: getver
        run: |
          version=$(curl -s https://pypi.org/pypi/duckdb/json | jq -r .info.version)
          echo "Latest DuckDB: $version"
          echo "version=$version" >> $GITHUB_OUTPUT

  build-test-release:
    name: Build & Publish to GHCR
    runs-on: ubuntu-latest
    needs: check-duckdb-version
    env:
      DUCKDB_VERSION: ${{ needs.check-duckdb-version.outputs.duckdb_version }}
      IMAGE_NAME: ghcr.io/${{ github.repository }}

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies for test
        run: |
          pip install -r requirements.txt
          pip install parse-wkb

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build --build-arg DUCKDB_VERSION=$DUCKDB_VERSION -t $IMAGE_NAME:$DUCKDB_VERSION .

      - name: Run tests in container
        run: |
          docker build -f Dockerfile.test -t duckdb-http-api:test .
          pytest tests/

      - name: Push image to GHCR
        run: |
          docker tag $IMAGE_NAME:$DUCKDB_VERSION $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$DUCKDB_VERSION
          docker push $IMAGE_NAME:latest

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.DUCKDB_VERSION }}
          name: "DuckDB ${{ env.DUCKDB_VERSION }}"
          body: |
            Docker image built with DuckDB version `${{ env.DUCKDB_VERSION }}`.
            Pulled from PyPI automatically.

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
